@echo off
set VCVARS=C:\PROGRA~1\MICROS~2\Common7\Tools\vsvars32.bat
call %VCVARS%
call "%WINDOWS_PLATFORM_SDK%\SetEnv.cmd" /XP32 /RETAIL
set JDK_DIR=C:/Java/j2sdk1.4.2_14
set PATH=%JAVA_1_4_2_HOME%\bin;%PATH%
set USE_VS2005=false
set EVC_ROOT=C:/PROGRA~1/MICROS~1.0
set EVC_COMMON_PATH=%EVC_ROOT%/Common/EVC/bin
set VC_SDK_TOOLS_PATH=%EVC_COMMON_PATH%
set WM5_SDK_INCLUDE=C:/PROGRA~1/WIEB7A~1/wce500/WINDOW~1.0PO/INCLUDE/ARMV4i
set WM5_SDK_LIB=C:/PROGRA~1/WIEB7A~1/wce500/WINDOW~1.0PO/LIB/ARMV4i
set EVC_ARM_INCLUDE=%WM5_SDK_INCLUDE%
set EVC_ARM_LIB=%WM5_SDK_LIB%
set EVC_ARM_PATH=%EVC_ROOT%/EVC/wce420/bin
Title Windows Mobile 5 Pocket PC SDK - ARM - eVC++ 4.0
