/* This file is auto generated by make file. Do not edit. */
#ifndef _PCSL_CONFIG_H_
#define _PCSL_CONFIG_H_

/* Enable datagram API */
#define PCSL_DATAGRAM
/* Enable server socket API */
#define PCSL_SERVER_SOCKET
/* File system module */
#define FILE_MODULE symbian
/* Network module */
#define NETWORK_MODULE stubs
/* Memory module */
#define MEMORY_MODULE malloc
/* Print module */
#define PRINT_MODULE stdout
/* String module */
#define STRING_MODULE utf16

#endif /*_PCSL_CONFIG_H_*/
