@echo off
set VCVARS=C:\PROGRA~1\MICROS~3\Common7\Tools\vsvars32.bat
call %VCVARS%
call "%WINDOWS_PLATFORM_SDK%\SetEnv.cmd" /XP32 /RETAIL
set JDK_DIR=c:/java/j2sdk1.4.2_14
set PATH=%JAVA_1_4_2_HOME%\bin;%PATH%
set USE_VS2005=false
set EVC_ROOT=C:/PROGRA~1/MICROS~1.0
set EVC_COMMON_PATH=%EVC_ROOT%/Common/EVC/bin
set VC_SDK_TOOLS_PATH=%EVC_COMMON_PATH%
set WM2003_SDK_INCLUDE=C:/PROGRA~1/WINDOW~4/wce420/POCKET~1/INCLUDE/ARMV4
set WM2003_SDK_LIB=C:/PROGRA~1/WINDOW~4/wce420/POCKET~1/LIB/ARMV4
set EVC_ARM_INCLUDE=%WM2003_SDK_INCLUDE%
set EVC_ARM_LIB=%WM2003_SDK_LIB%
set EVC_ARM_PATH=%EVC_ROOT%/EVC/wce420/bin
Title Windows Mobile 2003 Pocket PC SDK - ARM - eVC++ 4.0
